version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
    - ./src:/src
    - ./nodemon.json:/nodemon.json
    expose:
      - '5000'
    command: 'npm run dev'

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
 data: {}